# Generated by Django 4.2.2 on 2023-07-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_is_finished'),
        ('user', '0002_customuser_user_bookmarks_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_bookmarks',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
    ]
