# Generated by Django 4.2.2 on 2023-07-28 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_user_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_subscriptions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
