# Generated by Django 4.2.2 on 2023-07-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_finished',
            field=models.BooleanField(default=True),
        ),
    ]
